version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "65000:65000"
    restart: always
    volumes:
      - /opt/notion-text-snippets/logs:/docker/logs
      - /opt/notion-text-snippets/wallpaper:/docker/wallpaper